// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/courses": {
            "post": {
                "description": "Create a new course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Create course",
                "parameters": [
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.createCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.createCourseResponse"
                        }
                    }
                }
            }
        },
        "/api/courses/{courseId}": {
            "get": {
                "description": "Get details for a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Get course details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getCourseResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a course's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Update course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.updateCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.updateCourseResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Delete course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.deleteCourseResponse"
                        }
                    }
                }
            }
        },
        "/api/courses/{courseId}/staff": {
            "get": {
                "description": "Get all staff members for a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Get course staff",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getCourseStaffResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a staff member to a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Add staff to course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.addStaffToCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.addStaffToCourseResponse"
                        }
                    }
                }
            }
        },
        "/api/courses/{courseId}/staff/{staffId}": {
            "delete": {
                "description": "Remove a staff member from a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Remove staff from course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Staff ID",
                        "name": "staffId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.removeStaffFromCourseResponse"
                        }
                    }
                }
            }
        },
        "/api/courses/{courseId}/students": {
            "get": {
                "description": "Get all students for a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Get course students",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getCourseStudentsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a student to a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Add student to course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.addStudentToCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.addStudentToCourseResponse"
                        }
                    }
                }
            }
        },
        "/api/courses/{courseId}/students/{studentId}": {
            "delete": {
                "description": "Remove a student from a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Courses"
                ],
                "summary": "Remove student from course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.removeStudentFromCourseResponse"
                        }
                    }
                }
            }
        },
        "/api/grades/course/{courseId}": {
            "get": {
                "description": "Get a specific course grade for a student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Get course grade for a student",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getStudentCourseGradeResponse"
                        }
                    }
                }
            }
        },
        "/api/grades/exam": {
            "put": {
                "description": "Update an exam grade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Update exam grade",
                "parameters": [
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.updateExamGradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.updateExamGradeResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add an exam grade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Add exam grade",
                "parameters": [
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.addExamGradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.addExamGradeResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an exam grade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Delete exam grade",
                "parameters": [
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.deleteExamGradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.deleteExamGradeResponse"
                        }
                    }
                }
            }
        },
        "/api/grades/exam/{examId}": {
            "get": {
                "description": "Get a specific exam grade for a student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Get exam grade",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exam ID",
                        "name": "examId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getExamGradeResponse"
                        }
                    }
                }
            }
        },
        "/api/grades/homework": {
            "put": {
                "description": "Update a homework grade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Update homework grade",
                "parameters": [
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.updateHomeworkGradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.updateHomeworkGradeResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a homework grade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Add homework grade",
                "parameters": [
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.addHomeworkGradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.addHomeworkGradeResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a homework grade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Delete homework grade",
                "parameters": [
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.deleteHomeworkGradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.deleteHomeworkGradeResponse"
                        }
                    }
                }
            }
        },
        "/api/grades/homework/{homeworkId}": {
            "get": {
                "description": "Get a specific homework grade for a student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Get homework grade",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Homework ID",
                        "name": "homeworkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getHomeworkGradeResponse"
                        }
                    }
                }
            }
        },
        "/api/grades/{student_id}": {
            "get": {
                "description": "Get all grades for a student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Get all student grades",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NotImplementedYet"
                        }
                    }
                }
            }
        },
        "/api/grades/{student_id}/{courseId}": {
            "get": {
                "description": "Get grades for a student's course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Grades"
                ],
                "summary": "Get student's course grades",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getStudentCourseGradesResponse"
                        }
                    }
                }
            }
        },
        "/api/homework": {
            "post": {
                "description": "Create a new homework",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Homework"
                ],
                "summary": "Create homework",
                "parameters": [
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.createHomeworkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.createHomeworkResponse"
                        }
                    }
                }
            }
        },
        "/api/homework/{courseId}": {
            "get": {
                "description": "Get homework for a course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Homework"
                ],
                "summary": "Get homework",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getHomeworkResponse"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "Authenticate user and receive JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/staff": {
            "post": {
                "description": "Create a new staff member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Create staff member",
                "parameters": [
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.createStaffMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.createStaffMemberResponse"
                        }
                    }
                }
            }
        },
        "/api/staff/{staffId}": {
            "get": {
                "description": "Get details for a staff member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Get staff member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Staff ID",
                        "name": "staffId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getStaffMemberResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a staff member's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Update staff member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Staff ID",
                        "name": "staffId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.updateStaffMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.updateStaffMemberResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a staff member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Delete staff member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Staff ID",
                        "name": "staffId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.deleteStaffMemberResponse"
                        }
                    }
                }
            }
        },
        "/api/staff/{staffId}/courses": {
            "get": {
                "description": "Get all courses for a staff member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Get staff courses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Staff ID",
                        "name": "staffId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getStaffCoursesResponse"
                        }
                    }
                }
            }
        },
        "/api/students": {
            "post": {
                "description": "Create a new student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Create new student",
                "parameters": [
                    {
                        "description": "Student data",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.createStudentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.createStudentResponse"
                        }
                    }
                }
            }
        },
        "/api/students/{studentId}": {
            "get": {
                "description": "Get details for a student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Get student details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getStudentResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a student's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Update student",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Student ID",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.updateStudentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.updateStudentResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Delete student",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.deleteStudentResponse"
                        }
                    }
                }
            }
        },
        "/api/students/{studentId}/courses": {
            "get": {
                "description": "Get all courses for a student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Get student courses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.getStudentCoursesResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Course": {
            "type": "object",
            "required": [
                "name",
                "teacherId"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "students": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teacherId": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Grade": {
            "type": "object",
            "required": [
                "course_id",
                "score",
                "student_id"
            ],
            "properties": {
                "comments": {
                    "type": "string"
                },
                "course_id": {
                    "type": "string"
                },
                "graded_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "models.GradeSubmission": {
            "type": "object",
            "required": [
                "course_id",
                "score",
                "student_id"
            ],
            "properties": {
                "comments": {
                    "type": "string"
                },
                "course_id": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "models.Homework": {
            "type": "object",
            "required": [
                "course_id",
                "due_date",
                "title"
            ],
            "properties": {
                "course_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "models.NotImplementedYet": {
            "type": "object",
            "properties": {
                "not implemented yet": {
                    "type": "string"
                }
            }
        },
        "models.Staff": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "role"
            ],
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Course"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Student": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name"
            ],
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Course"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "models.addExamGradeRequest": {
            "type": "object",
            "required": [
                "exam_id",
                "grade_submission"
            ],
            "properties": {
                "exam_id": {
                    "type": "string"
                },
                "grade_submission": {
                    "$ref": "#/definitions/models.GradeSubmission"
                }
            }
        },
        "models.addExamGradeResponse": {
            "type": "object",
            "properties": {
                "grade": {
                    "$ref": "#/definitions/models.Grade"
                }
            }
        },
        "models.addHomeworkGradeRequest": {
            "type": "object",
            "required": [
                "grade_submission",
                "homework_id"
            ],
            "properties": {
                "grade_submission": {
                    "$ref": "#/definitions/models.GradeSubmission"
                },
                "homework_id": {
                    "type": "string"
                }
            }
        },
        "models.addHomeworkGradeResponse": {
            "type": "object",
            "properties": {
                "grade": {
                    "$ref": "#/definitions/models.Grade"
                }
            }
        },
        "models.addStaffToCourseRequest": {
            "type": "object",
            "required": [
                "id",
                "staffId"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "staffId": {
                    "type": "string"
                }
            }
        },
        "models.addStaffToCourseResponse": {
            "type": "object"
        },
        "models.addStudentToCourseRequest": {
            "type": "object",
            "required": [
                "id",
                "studentId"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "studentId": {
                    "type": "string"
                }
            }
        },
        "models.addStudentToCourseResponse": {
            "type": "object"
        },
        "models.createCourseRequest": {
            "type": "object",
            "required": [
                "id",
                "name",
                "teacherId"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "teacherId": {
                    "type": "string"
                }
            }
        },
        "models.createCourseResponse": {
            "type": "object",
            "properties": {
                "course": {
                    "$ref": "#/definitions/models.Course"
                }
            }
        },
        "models.createHomeworkRequest": {
            "type": "object",
            "required": [
                "course_id",
                "due_date",
                "homework_id",
                "title"
            ],
            "properties": {
                "course_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "homework_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.createHomeworkResponse": {
            "type": "object",
            "properties": {
                "homework": {
                    "$ref": "#/definitions/models.Homework"
                }
            }
        },
        "models.createStaffMemberRequest": {
            "type": "object",
            "properties": {
                "staff": {
                    "$ref": "#/definitions/models.Staff"
                }
            }
        },
        "models.createStaffMemberResponse": {
            "type": "object",
            "properties": {
                "staff": {
                    "$ref": "#/definitions/models.Staff"
                }
            }
        },
        "models.createStudentRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "id",
                "last_name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "models.createStudentResponse": {
            "type": "object",
            "properties": {
                "student": {
                    "$ref": "#/definitions/models.Student"
                }
            }
        },
        "models.deleteCourseResponse": {
            "type": "object"
        },
        "models.deleteExamGradeRequest": {
            "type": "object",
            "required": [
                "course_id",
                "exam_id",
                "student_id"
            ],
            "properties": {
                "course_id": {
                    "type": "string"
                },
                "exam_id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "models.deleteExamGradeResponse": {
            "type": "object"
        },
        "models.deleteHomeworkGradeRequest": {
            "type": "object",
            "required": [
                "course_id",
                "homework_id",
                "student_id"
            ],
            "properties": {
                "course_id": {
                    "type": "string"
                },
                "homework_id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "models.deleteHomeworkGradeResponse": {
            "type": "object"
        },
        "models.deleteStaffMemberResponse": {
            "type": "object"
        },
        "models.deleteStudentResponse": {
            "type": "object"
        },
        "models.getCourseResponse": {
            "type": "object",
            "properties": {
                "course": {
                    "$ref": "#/definitions/models.Course"
                }
            }
        },
        "models.getCourseStaffResponse": {
            "type": "object",
            "properties": {
                "staff": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.getCourseStudentsResponse": {
            "type": "object",
            "properties": {
                "students": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.getExamGradeResponse": {
            "type": "object",
            "properties": {
                "grade": {
                    "$ref": "#/definitions/models.Grade"
                }
            }
        },
        "models.getHomeworkGradeResponse": {
            "type": "object",
            "properties": {
                "grade": {
                    "$ref": "#/definitions/models.Grade"
                }
            }
        },
        "models.getHomeworkResponse": {
            "type": "object",
            "properties": {
                "homework": {
                    "$ref": "#/definitions/models.Homework"
                }
            }
        },
        "models.getStaffCoursesResponse": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Course"
                    }
                }
            }
        },
        "models.getStaffMemberResponse": {
            "type": "object",
            "properties": {
                "staff": {
                    "$ref": "#/definitions/models.Staff"
                }
            }
        },
        "models.getStudentCourseGradeResponse": {
            "type": "object",
            "properties": {
                "grade": {
                    "$ref": "#/definitions/models.Grade"
                }
            }
        },
        "models.getStudentCourseGradesResponse": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "string"
                },
                "grades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Grade"
                    }
                }
            }
        },
        "models.getStudentCoursesResponse": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Course"
                    }
                }
            }
        },
        "models.getStudentResponse": {
            "type": "object",
            "properties": {
                "student": {
                    "$ref": "#/definitions/models.Student"
                }
            }
        },
        "models.removeStaffFromCourseResponse": {
            "type": "object"
        },
        "models.removeStudentFromCourseResponse": {
            "type": "object"
        },
        "models.updateCourseRequest": {
            "type": "object",
            "required": [
                "id",
                "name",
                "teacherId"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "teacherId": {
                    "type": "string"
                }
            }
        },
        "models.updateCourseResponse": {
            "type": "object",
            "properties": {
                "course": {
                    "$ref": "#/definitions/models.Course"
                }
            }
        },
        "models.updateExamGradeRequest": {
            "type": "object",
            "required": [
                "exam_id",
                "grade_submission"
            ],
            "properties": {
                "exam_id": {
                    "type": "string"
                },
                "grade_submission": {
                    "$ref": "#/definitions/models.GradeSubmission"
                }
            }
        },
        "models.updateExamGradeResponse": {
            "type": "object",
            "properties": {
                "grade": {
                    "$ref": "#/definitions/models.Grade"
                }
            }
        },
        "models.updateHomeworkGradeRequest": {
            "type": "object",
            "required": [
                "grade_submission",
                "homework_id"
            ],
            "properties": {
                "grade_submission": {
                    "$ref": "#/definitions/models.GradeSubmission"
                },
                "homework_id": {
                    "type": "string"
                }
            }
        },
        "models.updateHomeworkGradeResponse": {
            "type": "object",
            "properties": {
                "grade": {
                    "$ref": "#/definitions/models.Grade"
                }
            }
        },
        "models.updateStaffMemberRequest": {
            "type": "object",
            "properties": {
                "staff": {
                    "$ref": "#/definitions/models.Staff"
                }
            }
        },
        "models.updateStaffMemberResponse": {
            "type": "object",
            "properties": {
                "staff": {
                    "$ref": "#/definitions/models.Staff"
                }
            }
        },
        "models.updateStudentRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "id",
                "last_name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "models.updateStudentResponse": {
            "type": "object",
            "properties": {
                "student": {
                    "$ref": "#/definitions/models.Student"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1234",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "BetterGR API Gateway",
	Description:      "Learning Management System API Gateway",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
